version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14 # Optional if you don't need Node.js
  build:
    commands:
      - echo "Nothing to build for static HTML"
artifacts:
  files:
    - '**/*'
  base-directory: . # deploy everything from root
